### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by N-Molham** [mohamedsobhy20/Calculator#2]
First of all, the is a big improvement than before which is a good thing.

## General
- [ ] None of the [code standards](https://bitbucket.org/teamyea/best-practices/wiki/Home) or best practices applied!

## HTML
- [x] Missing html close tag
- [x] extra spaces with between attributes and between some attributes `=` sign

## JavaScript
- [x] Code is running in the global scope with variables defined in the global scope which might cause issues with other scripts. It needs to running on it's own scope.
- [x] Code not formatted/organized well and difficult to read!
- [ ] Performance needs to be improved, for example: So many document queries for the same element(s) which aren't cached.
- [ ] Code needs to be more robust and dynamic, for example: so many click event callbacks which can be refactored to single callback with different logic within.
- [x] Start referring to CodePen [source code](http://codepen.io/NabeelMolham/pen/zZoxOX) to have better understanding of how it's done differently than your approach, which also might have room for improvement as well.

**Comment by mohamedsobhy20** [comment]
@N-Molham   i read your code nabeel and understand it well , enhancing performance and dynamism will force me to change the whole logic and redo the code from scratch .

**Comment by N-Molham** [comment]
You don't need to redo the whole thing from scratch, optimize and update what you have now.
